# Generated by Django 4.2.7 on 2023-11-09 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('name', models.TextField()),
                ('mstat', models.TextField(choices=[('str', 'Siła'), ('agi', 'Zręczność'), ('int', 'Inteligencja'), ('spi', 'Duchowość'), ('cns', 'Kondycja'), ('cha', 'Charyzma'), ('luk', 'Szczęście')])),
                ('sstat', models.TextField(choices=[('str', 'Siła'), ('agi', 'Zręczność'), ('int', 'Inteligencja'), ('spi', 'Duchowość'), ('cns', 'Kondycja'), ('cha', 'Charyzma'), ('luk', 'Szczęście')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Adventurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('subname', models.TextField()),
                ('origin', models.TextField()),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('healthcurrent', models.PositiveSmallIntegerField(default=30)),
                ('healthmax', models.PositiveSmallIntegerField(default=30)),
                ('str', models.PositiveSmallIntegerField(default=0)),
                ('agi', models.PositiveSmallIntegerField(default=0)),
                ('int', models.PositiveSmallIntegerField(default=0)),
                ('spi', models.PositiveSmallIntegerField(default=0)),
                ('cns', models.PositiveSmallIntegerField(default=0)),
                ('cha', models.PositiveSmallIntegerField(default=0)),
                ('luk', models.PositiveSmallIntegerField(default=0)),
                ('free_points', models.PositiveSmallIntegerField(default=2)),
                ('money', models.PositiveIntegerField()),
                ('honor', models.PositiveSmallIntegerField(default=0)),
                ('aclass', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='character.aclass')),
            ],
        ),
        migrations.CreateModel(
            name='AdventurerBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.adventurer')),
            ],
        ),
        migrations.CreateModel(
            name='ARace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('name', models.TextField()),
                ('rstat', models.TextField(choices=[('str', 'Siła'), ('agi', 'Zręczność'), ('int', 'Inteligencja'), ('spi', 'Duchowość'), ('cns', 'Kondycja'), ('cha', 'Charyzma'), ('luk', 'Szczęście')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wearing', models.BooleanField(default=False)),
                ('in_bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.adventurerbag')),
            ],
        ),
        migrations.CreateModel(
            name='BagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('icon', models.TextField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('countable', models.BooleanField(default=False)),
                ('bag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.adventurerbag')),
            ],
        ),
        migrations.AddField(
            model_name='adventurer',
            name='in_party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.party'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='character.arace'),
        ),
        migrations.AddField(
            model_name='adventurer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
