# Generated by Django 4.2.7 on 2023-11-10 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_alter_adventurer_aclass_alter_adventurer_money_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.TextField()),
                ('description', models.TextField()),
                ('reward', models.TextField()),
                ('reward_hidden', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.BooleanField(default=True)),
                ('skill_value_damage', models.PositiveSmallIntegerField(default=0, null=True)),
                ('skill_value_heal', models.PositiveSmallIntegerField(default=0, null=True)),
                ('skill_school', models.TextField(choices=[('ogień', 'ogień'), ('woda', 'woda'), ('mrok', 'mrok'), ('światło', 'światło'), ('fizyczne', 'fizyczne'), ('grom', 'grom'), ('magia', 'magia')])),
                ('skillimage', models.TextField(default='Icon.1_01.png')),
                ('skill_description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adventurerbag',
            name='daddy',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='in_bag',
        ),
        migrations.RemoveField(
            model_name='adventurer',
            name='healthmax',
        ),
        migrations.RemoveField(
            model_name='bagitem',
            name='bag',
        ),
        migrations.AddField(
            model_name='adventurer',
            name='exp',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bagitem',
            name='adventurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='character.adventurer'),
        ),
        migrations.DeleteModel(
            name='AdventurerBag',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
        migrations.AddField(
            model_name='quest',
            name='adventurer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.adventurer'),
        ),
        migrations.AddField(
            model_name='charskill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character.adventurer'),
        ),
        migrations.AddField(
            model_name='aclass',
            name='class_skills',
            field=models.ManyToManyField(related_name='classeswhoknow', to='character.skill'),
        ),
        migrations.AddField(
            model_name='arace',
            name='race_skills',
            field=models.ManyToManyField(related_name='raceswhoknow', to='character.skill'),
        ),
    ]
